think I figured out conforming dependencies, I had to try and start the server manually to get the real issue to surface, which was: java.lang.NoClassDefFoundError: BeanRegistrationExcludeFilter. Otherwise it just says: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet